from __future__ import annotations

import json
import re
import zipfile
from datetime import date
from io import BytesIO
from pathlib import Path
from typing import Any, Dict, Optional, List, Iterator, Tuple

import pandas as pd
import streamlit as st

# ============================================================
# BACKEND — DO NOT CHANGE
# ============================================================
from frontend.markdown_css import css
from backend.graph import app


# ============================================================
# PAGE CONFIG
# ============================================================
st.set_page_config(
    page_title="BlogForge",
    page_icon="✦",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# CUSTOM UI
# ============================================================
st.markdown(
    css,
    unsafe_allow_html=True,
)


# ============================================================
# HELPERS
# ============================================================
def safe_slug(title: str) -> str:
    s = title.strip().lower()
    s = re.sub(r"[^a-z0-9 _-]+", "", s)
    s = re.sub(r"\s+", "_", s).strip("_")
    return s or "blog"


def bundle_zip(md_text: str, md_filename: str, images_dir: Path) -> bytes:
    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr(md_filename, md_text.encode("utf-8"))

        if images_dir.exists() and images_dir.is_dir():
            for p in images_dir.rglob("*"):
                if p.is_file():
                    z.write(p, arcname=str(p))
    return buf.getvalue()


def images_zip(images_dir: Path) -> Optional[bytes]:
    if not images_dir.exists() or not images_dir.is_dir():
        return None

    buf = BytesIO()
    with zipfile.ZipFile(buf, "w", compression=zipfile.ZIP_DEFLATED) as z:
        for p in images_dir.rglob("*"):
            if p.is_file():
                z.write(p, arcname=str(p))
    return buf.getvalue()


def try_stream(graph_app, inputs: Dict[str, Any]) -> Iterator[Tuple[str, Any]]:
    """Stream graph progress if available; fallback to invoke()."""
    try:
        for step in graph_app.stream(inputs, stream_mode="updates"):
            yield ("updates", step)
        out = graph_app.invoke(inputs)
        yield ("final", out)
        return
    except Exception:
        pass

    try:
        for step in graph_app.stream(inputs, stream_mode="values"):
            yield ("values", step)
        out = graph_app.invoke(inputs)
        yield ("final", out)
        return
    except Exception:
        pass

    out = graph_app.invoke(inputs)
    yield ("final", out)


def extract_latest_state(
    current_state: Dict[str, Any],
    step_payload: Any,
) -> Dict[str, Any]:
    if isinstance(step_payload, dict):
        if (
            len(step_payload) == 1
            and isinstance(next(iter(step_payload.values())), dict)
        ):
            inner = next(iter(step_payload.values()))
            current_state.update(inner)
        else:
            current_state.update(step_payload)
    return current_state


_MD_IMG_RE = re.compile(r"!\[(?P<alt>[^\]]*)\]\((?P<src>[^)]+)\)")
_CAPTION_LINE_RE = re.compile(r"^\*(?P<cap>.+)\*$")


def _resolve_image_path(src: str) -> Path:
    src = src.strip().lstrip("./")
    return Path(src).resolve()


def render_markdown_with_local_images(md: str):
    """
    Render markdown while resolving images generated by the backend
    from the local images/ directory.
    """
    matches = list(_MD_IMG_RE.finditer(md))

    if not matches:
        st.markdown(md, unsafe_allow_html=False)
        return

    parts: List[Tuple[str, str]] = []
    last = 0

    for m in matches:
        before = md[last:m.start()]
        if before:
            parts.append(("md", before))

        alt = (m.group("alt") or "").strip()
        src = (m.group("src") or "").strip()
        parts.append(("img", f"{alt}|||{src}"))
        last = m.end()

    tail = md[last:]
    if tail:
        parts.append(("md", tail))

    i = 0

    while i < len(parts):
        kind, payload = parts[i]

        if kind == "md":
            st.markdown(payload, unsafe_allow_html=False)
            i += 1
            continue

        alt, src = payload.split("|||", 1)
        caption = None

        if i + 1 < len(parts) and parts[i + 1][0] == "md":
            nxt = parts[i + 1][1].lstrip()

            if nxt.strip():
                first_line = nxt.splitlines()[0].strip()
                mcap = _CAPTION_LINE_RE.match(first_line)

                if mcap:
                    caption = mcap.group("cap").strip()
                    rest = "\n".join(nxt.splitlines()[1:])
                    parts[i + 1] = ("md", rest)

        if src.startswith("http://") or src.startswith("https://"):
            st.image(
                src,
                caption=caption or (alt or None),
                use_container_width=True,
            )
        else:
            img_path = _resolve_image_path(src)

            if img_path.exists():
                st.image(
                    str(img_path),
                    caption=caption or (alt or None),
                    use_container_width=True,
                )
            else:
                st.warning(
                    f"Image not found: `{src}` "
                    f"(looked for `{img_path}`)"
                )

        i += 1


def list_past_blogs() -> List[Path]:
    cwd = Path(".")
    files = [p for p in cwd.glob("*.md") if p.is_file()]
    files.sort(key=lambda p: p.stat().st_mtime, reverse=True)
    return files


def read_md_file(p: Path) -> str:
    return p.read_text(encoding="utf-8", errors="replace")


def extract_title_from_md(md: str, fallback: str) -> str:
    for line in md.splitlines():
        if line.startswith("# "):
            title = line[2:].strip()
            return title or fallback
    return fallback


def get_plan_dict(plan_obj: Any) -> Optional[dict]:
    if not plan_obj:
        return None

    if hasattr(plan_obj, "model_dump"):
        return plan_obj.model_dump()

    if isinstance(plan_obj, dict):
        return plan_obj

    try:
        return json.loads(json.dumps(plan_obj, default=str))
    except Exception:
        return None


def article_title(out: dict) -> str:
    final_md = out.get("final") or ""
    plan_dict = get_plan_dict(out.get("plan"))

    if plan_dict:
        return plan_dict.get(
            "blog_title",
            extract_title_from_md(final_md, "Untitled article"),
        )

    return extract_title_from_md(final_md, "Untitled article")


def reset_workspace():
    st.session_state["last_out"] = None
    st.session_state["generation_running"] = False
    st.session_state["active_view"] = "create"


# ============================================================
# SESSION STATE
# ============================================================
if "last_out" not in st.session_state:
    st.session_state["last_out"] = None

if "active_view" not in st.session_state:
    st.session_state["active_view"] = "create"

if "generation_running" not in st.session_state:
    st.session_state["generation_running"] = False

if "logs" not in st.session_state:
    st.session_state["logs"] = []


# ============================================================
# SIDEBAR
# ============================================================
with st.sidebar:
    st.markdown(
        """
        <div class="brand">
            <span class="brand-mark">✦</span>BlogForge
        </div>
        """,
        unsafe_allow_html=True,
    )

    if st.button("＋  New article", use_container_width=True):
        reset_workspace()
        st.rerun()

    st.markdown(
        '<div class="sidebar-label">Your articles</div>',
        unsafe_allow_html=True,
    )

    past_files = list_past_blogs()

    if not past_files:
        st.markdown(
            '<div class="small-muted">No saved articles yet.</div>',
            unsafe_allow_html=True,
        )
    else:
        for p in past_files[:12]:
            try:
                title = extract_title_from_md(read_md_file(p), p.stem)
            except Exception:
                title = p.stem

            st.markdown(
                f'<div class="sidebar-blog">• {title[:34]}</div>',
                unsafe_allow_html=True,
            )

    st.markdown(
        '<div class="sidebar-label">About</div>',
        unsafe_allow_html=True,
    )

    st.markdown(
        """
        <div class="small-muted">
            AI-powered technical blog generation using your existing
            LangGraph workflow.
        </div>
        """,
        unsafe_allow_html=True,
    )


# ============================================================
# CREATE VIEW
# ============================================================
out = st.session_state.get("last_out")

if not out:
    left, right = st.columns([1.45, 0.55])

    with left:
        st.markdown(
            """
            <div class="hero">
                <div class="eyebrow">AI writing workspace</div>
                <h1>Turn an idea into a publish-ready article.</h1>
                <p>
                    Research, structure, writing and technical visuals —
                    generated through your existing LangGraph workflow.
                </p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown(
            '<div class="input-label">ARTICLE TOPIC</div>',
            unsafe_allow_html=True,
        )

        topic = st.text_area(
            "Topic",
            height=170,
            placeholder=(
                "Example: Build a production-ready RAG application "
                "with LangGraph..."
            ),
            label_visibility="collapsed",
        )

        c1, c2, c3 = st.columns(3)

        with c1:
            audience = st.selectbox(
                "Audience",
                [
                    "Developers",
                    "Technical leaders",
                    "AI/ML engineers",
                    "Beginners",
                    "General readers",
                ],
            )

        with c2:
            tone = st.selectbox(
                "Tone",
                [
                    "Professional",
                    "Conversational",
                    "Technical",
                    "Educational",
                    "Opinionated",
                ],
            )

        with c3:
            as_of = st.date_input(
                "As-of date",
                value=date.today(),
            )

        st.markdown(
            """
            <div style="margin-top:12px;">
                <span class="chip">Research automatically decided</span>
                <span class="chip">Technical diagrams</span>
                <span class="chip">Markdown output</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown("<div style='height:12px'></div>", unsafe_allow_html=True)

        generate = st.button(
            "✦  Generate article",
            type="primary",
            use_container_width=True,
        )

    with right:
        st.markdown(
            '<div class="section-title">How it works</div>',
            unsafe_allow_html=True,
        )

        steps = [
            ("01", "Understand", "Classifies the topic and decides research mode."),
            ("02", "Research", "Finds current evidence when needed."),
            ("03", "Plan", "Builds a structured article outline."),
            ("04", "Write", "Generates each section in parallel."),
            ("05", "Visualize", "Adds useful technical diagrams."),
        ]

        for number, title, description in steps:
            st.markdown(
                f"""
                <div class="meta-card">
                    <div class="meta-label">{number}</div>
                    <div class="meta-value">{title}</div>
                    <div class="small-muted">{description}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

    st.markdown(
        '<div class="section-title">Recent articles</div>',
        unsafe_allow_html=True,
    )

    if past_files:
        cols = st.columns(3)

        for idx, p in enumerate(past_files[:6]):
            try:
                md = read_md_file(p)
                title = extract_title_from_md(md, p.stem)
                words = len(md.split())
                modified = date.fromtimestamp(p.stat().st_mtime)
            except Exception:
                title = p.stem
                words = 0
                modified = date.today()

            with cols[idx % 3]:
                st.markdown(
                    f"""
                    <div class="library-card">
                        <div class="library-title">{title}</div>
                        <div class="library-meta">
                            {words:,} words · {modified.strftime("%d %b %Y")}
                        </div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

                if st.button(
                    "Open",
                    key=f"open_{idx}_{p.name}",
                    use_container_width=True,
                ):
                    st.session_state["last_out"] = {
                        "plan": None,
                        "evidence": [],
                        "image_specs": [],
                        "final": md,
                    }
                    st.rerun()
    else:
        st.markdown(
            '<div class="small-muted">Your generated articles will appear here.</div>',
            unsafe_allow_html=True,
        )

    # --------------------------------------------------------
    # GENERATE
    # --------------------------------------------------------
    if generate:
        if not topic.strip():
            st.warning("Please enter a topic first.")
            st.stop()

        inputs: Dict[str, Any] = {
            "topic": topic.strip(),
            "mode": "",
            "needs_research": False,
            "queries": [],
            "evidence": [],
            "plan": None,
            "as_of": as_of.isoformat(),
            "recency_days": 7,
            "sections": [],
            "merged_md": "",
            "md_with_placeholders": "",
            "image_specs": [],
            "final": "",
        }

        st.session_state["generation_running"] = True

        st.markdown(
            '<div class="section-title">Creating your article</div>',
            unsafe_allow_html=True,
        )

        status = st.status(
            "Generating article…",
            expanded=True,
        )

        progress_area = st.empty()
        current_state: Dict[str, Any] = {}
        last_node = None
        logs: List[str] = []

        node_labels = {
            "router": "Understanding topic",
            "research": "Researching sources",
            "orchestrator": "Building article plan",
            "worker": "Writing article sections",
            "reducer": "Combining sections",
            "merge_content": "Combining article",
            "decide_images": "Planning technical visuals",
            "generate_and_place_images": "Generating visuals",
        }

        for kind, payload in try_stream(app, inputs):
            if kind in ("updates", "values"):
                node_name = None

                if (
                    isinstance(payload, dict)
                    and len(payload) == 1
                    and isinstance(next(iter(payload.values())), dict)
                ):
                    node_name = next(iter(payload.keys()))

                if node_name and node_name != last_node:
                    label = node_labels.get(
                        node_name,
                        node_name.replace("_", " ").title(),
                    )
                    status.write(f"✓ {label}")
                    last_node = node_name

                current_state = extract_latest_state(
                    current_state,
                    payload,
                )

                summary = {
                    "mode": current_state.get("mode"),
                    "needs_research": current_state.get("needs_research"),
                    "queries": current_state.get("queries", [])[:5]
                    if isinstance(current_state.get("queries"), list)
                    else [],
                    "evidence_count": len(
                        current_state.get("evidence", []) or []
                    ),
                    "tasks": len(
                        (current_state.get("plan") or {}).get("tasks", [])
                    )
                    if isinstance(current_state.get("plan"), dict)
                    else None,
                    "images": len(
                        current_state.get("image_specs", []) or []
                    ),
                    "sections_done": len(
                        current_state.get("sections", []) or []
                    ),
                }

                progress_area.json(summary)
                logs.append(
                    f"[{kind}] "
                    f"{json.dumps(payload, default=str)[:1200]}"
                )

            elif kind == "final":
                st.session_state["last_out"] = payload
                st.session_state["logs"].extend(logs)
                st.session_state["generation_running"] = False

                status.update(
                    label="Article ready",
                    state="complete",
                    expanded=False,
                )

                st.rerun()


# ============================================================
# ARTICLE VIEW
# ============================================================
else:
    final_md = out.get("final") or ""
    title = article_title(out)
    plan_dict = get_plan_dict(out.get("plan"))
    evidence = out.get("evidence") or []
    image_specs = out.get("image_specs") or []

    # Top navigation
    st.markdown(
        f"""
        <div class="topbar">
            <div>
                <div class="eyebrow" style="margin-bottom:4px;">
                    ARTICLE
                </div>
                <div class="topbar-title">{title}</div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    top1, top2, top3, top4 = st.columns([1.4, 1, 1, 1])

    with top1:
        if st.button("← Back to workspace"):
            st.session_state["last_out"] = None
            st.rerun()

    with top2:
        md_filename = f"{safe_slug(title)}.md"
        st.download_button(
            "↓ Markdown",
            data=final_md.encode("utf-8"),
            file_name=md_filename,
            mime="text/markdown",
            use_container_width=True,
        )

    with top3:
        bundle = bundle_zip(
            final_md,
            md_filename,
            Path("images"),
        )
        st.download_button(
            "↓ Bundle",
            data=bundle,
            file_name=f"{safe_slug(title)}_bundle.zip",
            mime="application/zip",
            use_container_width=True,
        )

    with top4:
        if st.button("↻ New article", use_container_width=True):
            st.session_state["last_out"] = None
            st.rerun()

    main, aside = st.columns([1.55, 0.45], gap="large")

    # --------------------------------------------------------
    # ARTICLE
    # --------------------------------------------------------
    with main:
        st.markdown('<div class="article-shell">', unsafe_allow_html=True)

        if final_md:
            render_markdown_with_local_images(final_md)
        else:
            st.warning("No final markdown was returned.")

        st.markdown("</div>", unsafe_allow_html=True)

    # --------------------------------------------------------
    # ARTICLE INFO / NAV
    # --------------------------------------------------------
    with aside:
        st.markdown(
            '<div class="section-title" style="margin-top:0;">Overview</div>',
            unsafe_allow_html=True,
        )

        if plan_dict:
            meta = [
                ("Audience", plan_dict.get("audience", "—")),
                ("Tone", plan_dict.get("tone", "—")),
                ("Type", plan_dict.get("blog_kind", "—")),
                (
                    "Sections",
                    str(len(plan_dict.get("tasks", []) or [])),
                ),
                ("Sources", str(len(evidence))),
                ("Visuals", str(len(image_specs))),
            ]

            for label, value in meta:
                st.markdown(
                    f"""
                    <div class="meta-card">
                        <div class="meta-label">{label}</div>
                        <div class="meta-value">{value}</div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )

        # Sources
        st.markdown(
            '<div class="section-title" style="font-size:18px;">Sources</div>',
            unsafe_allow_html=True,
        )

        if evidence:
            for e in evidence[:10]:
                if hasattr(e, "model_dump"):
                    e = e.model_dump()

                source_title = e.get("title") or "Source"
                source_url = e.get("url") or ""

                st.markdown(
                    f"""
                    <div class="source-item">
                        <div class="source-title">{source_title}</div>
                        <div class="source-url">{source_url}</div>
                    </div>
                    """,
                    unsafe_allow_html=True,
                )
        else:
            st.markdown(
                '<div class="small-muted">No research sources returned.</div>',
                unsafe_allow_html=True,
            )

        # Images
        images_dir = Path("images")

        if image_specs or images_dir.exists():
            st.markdown(
                '<div class="section-title" style="font-size:18px;">Assets</div>',
                unsafe_allow_html=True,
            )

            if images_dir.exists():
                files = [
                    p for p in images_dir.iterdir()
                    if p.is_file()
                ]

                if files:
                    st.caption(f"{len(files)} generated image(s)")

                    for p in sorted(files):
                        st.image(
                            str(p),
                            caption=p.name,
                            use_container_width=True,
                        )

                    z = images_zip(images_dir)

                    if z:
                        st.download_button(
                            "↓ Download images",
                            data=z,
                            file_name="images.zip",
                            mime="application/zip",
                            use_container_width=True,
                        )


# ============================================================
# OPTIONAL DEBUG DETAILS
# ============================================================
if out:
    with st.expander("Generation details"):
        plan_dict = get_plan_dict(out.get("plan"))

        if plan_dict:
            st.markdown("### Plan")
            st.json(plan_dict)

        if out.get("evidence"):
            st.markdown("### Evidence")
            rows = []

            for e in out.get("evidence") or []:
                if hasattr(e, "model_dump"):
                    e = e.model_dump()

                rows.append(
                    {
                        "title": e.get("title"),
                        "published_at": e.get("published_at"),
                        "source": e.get("source"),
                        "url": e.get("url"),
                    }
                )

            st.dataframe(
                pd.DataFrame(rows),
                use_container_width=True,
                hide_index=True,
            )

        if out.get("image_specs"):
            st.markdown("### Image plan")
            st.json(out.get("image_specs"))

        if st.session_state.get("logs"):
            st.markdown("### Logs")
            st.text_area(
                "Event log",
                value="\n\n".join(
                    st.session_state["logs"][-80:]
                ),
                height=350,
                label_visibility="collapsed",
            )
